version: '3.8'

services:
    server:
        container_name: server
        image: dockerhubenrique/dockerhub:server_socket:1.0.1
        ports:
            - "${SERVER_PORT:-8080}:8080"
        environment:
            - SERVER_PORT=${SERVER_PORT:-8080}
            - SERVER_HOST=server
            - BUFFER_SIZE=${BUFFER_SIZE:-2048}
        networks:
            - app-network
    client:
        container_name: client
        image: dockerhubenrique/dockerhub:client_socket:1.0.1
        environment:
            - SERVER_PORT=${SERVER_PORT:-8080}
            - SERVER_HOST=server
            - BUFFER_SIZE=${BUFFER_SIZE:-2048}
        depends_on:
            - server
        networks:
            - app-network

networks:
    app-network:
        name: app-network
        driver: bridge
