version: '3.8'

services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - SERVER_PORT=8080
            - SERVER_HOST=server
            - BUFFER_SIZE=2048
        networks:
            - app-network
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=8080
            - SERVER_HOST=server
            - BUFFER_SIZE=2048
        depends_on:
            - server
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
