version: '3.8'

services:
    server:
        container_name: server
        image: dockerhubenrique/dockerhub:server_socket
        ports:
            - "${SERVER_PORT}:8080"
        environment:
            - SERVER_PORT=8080
            - SERVER_HOST=server
            - BUFFER_SIZE=2048
        networks:
            - app-network
    client:
        container_name: client
        image: dockerhubenrique/dockerhub:client_socket
        environment:
            - SERVER_PORT=8080
            - SERVER_HOST=server
            - BUFFER_SIZE=2048
        depends_on:
            - server
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
